openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://young-cove-79509.herokuapp.com/
    description: Optional server description, e.g. Main (production) server
paths:
  /api/users/register:
    post:
      summary: Registers a user and provides a jwt token for uploading images
      description: Provide name, email and password and create an account for adding images to image rep
      parameters:
      - in: "body"
        name: body
        description: Credentials object needed to register for an account
        schema:
          type: object
          properties:
            name:
              type: string
              example: testuser
            email:
              type: string
              example: testuser@gmail.com
            password:
              type: string
              example: password
      responses:
        '200':    # status code
          description: A JSON object containing your user object and a jwt token valid for 1 hour
          content:
            application/json:
              schema: 
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.elYTVjODY4MGRlMDg1ODQwNjZkYyIsImlhdCI6MTYyMDQ1MDM0NSwiZXhwIjoxNjIwNDUzOTQ1fQ.qWF4jABj9NLv2vfKcKI_CoGB0_gg5vpTOE2IXG4xDo4
                  user:
                    type: object
                    properties:
                      name: 
                        type: string
                        example: loggedInUser
                      email: 
                        type: string
                        example: loggedInUser@gmail.com
                      id: 
                        type: string
                        example: 6089ea5c8680de08584066dc